#cloud-config
debug: true
disable_root: false
#manage_etc_hosts: true
apt_update: true
package_upgrade: true
packages:
growpart:
    mode: auto
    devices: ['/']
    ignore_growroot_disabled: false
bootcmd:
write_files:
runcmd:
    # just let the ASG reboot this box every Saturday
    #- echo "/sbin/halt" | /usr/bin/at midnight $$(date -d 'next Saturday' '+%Y-%m-%d')
    - docker run -d -p 5000:5000 --restart=always --privileged --name registry -e "REGISTRY_STORAGE=gcs" -e "REGISTRY_STORAGE_GCS_BUCKET=insurance-${env}" -e "REGISTRY_STORAGE_GCS_ROOTDIRECTORY=/registry" registry:2
